name: iOS PR Library

on: [push]

jobs:
  build:
    name: Run Unit Tests
    runs-on: macos-11

    steps:
        - uses: actions/checkout@v1
        - name: Select Xcode
          run: sudo xcode-select -switch /Applications/Xcode_14.2.app && /usr/bin/xcodebuild -version
        - name: Run tests
          run: xcodebuild test -scheme iOSTestFlightGithubActions -project iOSTestFlightGithubActions.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14,OS=14.0' | xcpretty && exit ${PIPESTATUS[0]}